volumes:
  redis_data:
  virtuoso_data:

services:
  traefik:
    image: traefik:2.11
    command:
      # - '--log.level=DEBUG'
      - '--log.level=INFO'
      - '--api.insecure=true'
      - '--api.dashboard=true'
      # Docker
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      # Dynamic config
      - '--providers.file.filename=/etc/traefik/config.yaml'
      # Entrypoints
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      # Redirect HTTP to HTTPS
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/config.yaml:/etc/traefik/config.yaml:ro
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      # Dashboard
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.music-event-connect.localhost`)'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.entrypoints=websecure'
      - 'traefik.http.routers.dashboard.tls=true'

  virtuoso:
    image: openlink/virtuoso-opensource-7:7
    ports:
      # HTTP/SPARQL endpoint
      - '8890:8890'
      # iSQL command-line tool
      - '1111:1111'
    volumes:
      # Database files
      - virtuoso_data:/database
      # Initialization scripts
      - ./virtuoso/scripts:/import/scripts:ro
      # Initial RDF data to be loaded
      - ./rdf-data:/import/data:ro
    environment:
      # Set `dba` user password (also sets `dav` user password if DAV_PASSWORD not set)
      - DBA_PASSWORD=pass123word
      # Allow Virtuoso to load initial data from custom directory
      - VIRT_Parameters_DirsAllowed=.,../vad,/usr/share/proj,/import
      # Uncomment and edit these values for initial data bulk-load (adjust according to available RAM)
      # - VIRT_Parameters_NumberOfBuffers=300000
      # - VIRT_Parameters_MaxDirtyBuffers=100000
      # When there is 2 GB of RAM free
      - VIRT_Parameters_NumberOfBuffers=170000
      - VIRT_Parameters_MaxDirtyBuffers=130000
    healthcheck:
      test: ['CMD-SHELL', 'nc -z localhost 1111 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.virtuoso-web.rule=Host(`music-event-connect.localhost`) && (PathPrefix(`/sparql`) || PathPrefix(`/sparql-auth`))'
      - 'traefik.http.routers.virtuoso-web.entrypoints=websecure'
      - 'traefik.http.routers.virtuoso-web.tls=true'
      - 'traefik.http.services.virtuoso-web.loadbalancer.server.port=8890'

  redis:
    image: redis:alpine3.22
    volumes:
      - redis_data:/data
    restart: unless-stopped

  handler:
    image: music-event-connect-handler:devel
    build:
      context: .
      dockerfile: ./apps/handler/Dockerfile
      target: development
    command: pnpm start:dev
    volumes:
      - ./configs/config-handler.yaml:/app/apps/handler/config.yaml:ro
      - ./logs/handler:/app/apps/handler/logs:rw
    depends_on:
      virtuoso:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  scraper:
    image: music-event-connect-scraper:devel
    build:
      context: .
      dockerfile: ./apps/scraper/Dockerfile
      target: development
    command: pnpm start:dev
    volumes:
      - ./configs/config-scraper.yaml:/app/apps/scraper/config.yaml:ro
      - ./logs/scraper:/app/apps/scraper/logs:rw
    depends_on:
      - redis
    restart: unless-stopped

  api:
    image: music-event-connect-api:devel
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: pnpm start:dev
    ports:
      - '3060:3060'
    volumes:
      - ./configs/config-api.yaml:/app/apps/api/config.yaml:ro
      - ./logs/api:/app/apps/api/logs:rw
    depends_on:
      virtuoso:
        condition: service_healthy
    restart: unless-stopped

  web:
    image: music-event-connect-web:devel
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    command: pnpm start:dev
    volumes:
      - ./configs/config-web.json:/app/apps/web/public/config.json:ro
      - ./logs/web:/app/apps/web/logs:rw
      - ./apps/web/public:/app/apps/web/public:ro
      - ./apps/web/src:/app/apps/web/src:ro
    ports:
      # expose port for Vite HMR
      - '3030:3030'
    environment:
      - NODE_ENV=development
      - PORT=3030
    depends_on:
      traefik:
        condition: service_started
      virtuoso:
        condition: service_healthy
      api:
        condition: service_started
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.web.rule=Host(`music-event-connect.localhost`)'
      - 'traefik.http.routers.web.entrypoints=websecure'
      - 'traefik.http.routers.web.tls=true'
      - 'traefik.http.services.web.loadbalancer.server.port=3030'
