# Node environment (development|production)
nodeEnv:

# Port for the app to run on
port:

# CORS
cors:
  # array of CORS allowed origins
  allowedOrigins:

# Rate limiting
throttler:
  # time-to-live (TTL) in seconds that each request will last in storage (0 = infinite)
  ttl:
  # max. amount of requests client can make in given TTL
  limit:

# Triple store
tripleStore:
  # full SPARQL read endpoint URL
  endpointUrl:
  # authorization
  user:
  password:
